# FROM python:3.8-slim-bullseye
FROM python:3.8

# dockerize with:
# > docker build -t real-aesthete-base -f Dockerfile-base .
# > docker buildx build --platform=linux/arm/v7 -t real-aesthete-base-arm -f Dockerfile-base .

COPY ./Pipfile .
COPY ./Pipfile.lock .
RUN pip install pipenv
RUN pipenv install --system --deploy --ignore-pipfile

# ENTRYPOINT python main.py